### ISSUE TITLE
Initial State from Local Storage

### ISSUE THREAD

**Issue by gagalina** [evgeniivall/notes-app-ui#16]
https://github.com/evgeniivall/notes-app-ui/blob/603fdf8df9a7982397e19541d239597c6d622b0b/src/features/notes/notesSlice.js#L14

Ensure that notes is always initialized as an array:
`notes: loadFromLocalStorage('notes') || [],`

**Comment by evgeniivall** [comment]
Empty array is retuned from loadFromLocalStorage()
